# .travis.yml
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

addons:
  code_climate:
    repo_token: 08911cac0ac4ce423ce0c7504086292c45bd80441eeb35725e6c6d9898

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit

after_script:
  - vendor/bin/test-reporter
